import pandas as pd
from lark import Tree

def get_decoding(traces, regions, tasks):
    """
    Decoding traces generated

    Parameters
    ----------
    traces
        list of traces encoded (ex. t generated by transformer)
    regions (actually useless)
        regions of the process/net
    tasks
        tasks of the process/net

    Returns
    ----------
    traces_decoded
    traces_decoded
        list with traces decoded (ex. ['start_T1', .... , 'end_T8'])
    """

    traces_decoded = []

    for t in traces:
        trace_decoded = []
        #regions_previous = [0] * len(regions)
        tasks_previous = [0] * len(tasks)

        for step in t:
            #regions_step = step[0:len(regions)]
            tasks_step = step[len(regions):]

            for i, task in enumerate(tasks_step): #Guardo la task/le task diverse rispetto allo step precedente
                if task != tasks_previous[i]:
                    if task == 1: #Aggiungo o l'inizio della task o la fine della task
                        trace_decoded.append("start_"+tasks[i])
                    else:
                        trace_decoded.append("end_"+tasks[i])

            #regions_previous = regions_step
            tasks_previous = tasks_step

        traces_decoded.append(trace_decoded)

    return traces_decoded

def get_encoding(traces, regions, tasks, open_clauses, end_clauses):
    """
    Encoding traces generated
    1 --> if task/region starts or is executed in current step
    0 --> if task/region ends or is not executed in current step

    end_L cases will modify only the loop region's bit of the previous column

    Parameters
    ----------
    traces
        traces generated
    regions
        regions of the process/net
    tasks
        tasks of the process/net
    open_clauses
        opening clauses of the regions/tasks
    end_clauses
        ending clauses of the regions/tasks

    Returns
    ----------
    df_regions, df_tasks
    df_regions
        dataframe with trace regions encoded
    df_tasks
        dataframe with trace tasks encoded
    """
    #Inizializzo le matrici per la codifica delle tracce (regioni e task)
    traceEncoded_regions = {r: [] for r in regions}
    traceEncoded_tasks = {t: [] for t in tasks}

    loop_ends_counter = 0 # Per capire quanto indietro andare ogni volta rispetto allo step attuale (cioè quante colonne abbiamo effettivamente saltato)
    trace_step_counter = 0

    for trace in traces:
        first_step = True
        ended_tasks = [] # Inseriamo anche gli end loop

        for i, step in enumerate(trace):
            skip = False
            #regions_step = regions.copy() #Per tenere 'traccia' (brutto gioco di parole) delle ragioni che finiscono o iniziano nello step corrente
            regions_step = set(regions)

            current_task = step.split("_")[1] #Prendo la current_task per aiutarmi nel traceEncoded_tasks

            if step.startswith("start"):
                traceEncoded_tasks[current_task].append(1) #Se task inizia allo step corrente, il suo valore nella matrice diventa 1 (prima e precedente era 0)
                for key, clauses in open_clauses.items(): #Se l'inizio del task appartiene all'open_clauses di una regione, il valore codificato della matrice è 1
                    if {step} in clauses:
                        regions_step.remove(key)
                        traceEncoded_regions[key].append(1)
            else:
                ended_tasks.append(step)
                ended_tasks_set = set(ended_tasks)

                # Genero tutte le combinazioni possibili di task finite per controllare se alcuni regioni finiscono allo step corrente (potrei avere una combinazione di end di task)
                '''combinations = [
                    set(c)
                    for i in range(2, len(ended_tasks) + 1)
                    for c in itertools.combinations(ended_tasks, i)
                ]
                combinations.append({step})'''  # Aggiungo la singola end task dello step corrente (potrebbe chiudere da sola una o più regioni)

                if step.startswith("end_L"):  # Se è un end loop aggiorno il bit del loop region di prima --> da 1 metto 0
                    loop_ends_counter += 1
                    region = "R" + step.split("end_L")[1]
                    traceEncoded_regions[region][trace_step_counter + i - loop_ends_counter] = 0
                    skip = True

                    for key, clauses in end_clauses.items(): #Guardo se il loop ha causato chiusure al tempo precedente
                        for clause in clauses:  # Clause è un set, es: {'end_T1', 'end_T2'}
                            if step in clause and clause.issubset(ended_tasks_set): # Se lo step corrente fa parte della clausola E tutti gli elementi della clausola sono nei task finiti
                                traceEncoded_regions[key][trace_step_counter + i - loop_ends_counter] = 0
                                break

                else:
                    traceEncoded_tasks[current_task].append(0) #Se task finisce  allo step corrente, il suo valore nella matrice diventa 0 (prima e precedente era 1)

                    for key, clauses in end_clauses.items(): #Se una delle combinazioni appartiene all'end_clauses di una regione, il valore codificato della matrice torna 0
                        for clause in clauses:  # Clause è un set, es: {'end_T1', 'end_T2'}
                            if step in clause and clause.issubset(ended_tasks_set):  # Se lo step corrente fa parte della clausola E tutti gli elementi della clausola sono nei task finiti
                                regions_step.remove(key)
                                traceEncoded_regions[key].append(0)
                                break

            if not skip:
                for region in regions_step: #Sistemo le regioni non considerate fino ad ora dallo step corrente (0 se siamo al primo step, altrimenti prendiamo il valore precedente --> se una regione è iniziata allo step precedente e non è finita, il valore deve rimanere 1)
                    if first_step:
                        traceEncoded_regions[region].append(0)
                    else:
                        traceEncoded_regions[region].append(traceEncoded_regions[region][-1])

                for task in tasks: #Stessa cosa delle regioni, fatta per i task
                    if first_step and task!=current_task:
                        traceEncoded_tasks[task].append(0)
                    elif task!=current_task:
                        traceEncoded_tasks[task].append(traceEncoded_tasks[task][-1])

            first_step = False

        trace_step_counter += len(trace)

    #Creo i due dataframe codificati delle regioni e delle task
    df_regions = pd.DataFrame(traceEncoded_regions).T
    df_tasks = pd.DataFrame(traceEncoded_tasks).T

    return df_regions, df_tasks


def compute_process_complexity(tree):
    """
    Returns (nested, parallel):
    - nested:   max depth of XOR/loop nesting (one inside another)
    - parallel: max total XOR/loop decisions concurrent across parallel branches
    """
    if tree.data == 'xor':
        n, p = 0, 0
        for child in tree.children:
            nc, pc = compute_process_complexity(child)
            if nc > n: n=nc
            if pc > p: p=pc
        return 1 + n, p
    elif tree.data == 'loop':
        child = tree.children[0]
        n, p = compute_process_complexity(child)
        return 1 + n, p
    elif tree.data == 'parallel':
        n, p = 0, 0
        for child in tree.children:
            nc, pc = compute_process_complexity(child)
            if nc > n: n = nc
            p += pc
        return n, p
    elif tree.data == 'sequential':
        n, p = 0, 0
        for child in tree.children:
            nc, pc = compute_process_complexity(child)
            if nc > n: n = nc
            if pc > p: p = pc
        return n, p
    else: # siamo nel task
        return 0, 1
